In [2]:
import pandas as pd
titanic_dataset_local_url = "titanic.csv"
df = pd.read_csv(titanic_dataset_local_url)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [2]:
# String method to replace the text in the string
import pandas as pd
titanic_dataset_local_url = "titanic.csv"
df = pd.read_csv(titanic_dataset_local_url)
df.head()

new =df['Name'].str.replace("Mr.","Sir", regex=False)

In [3]:
df.loc[1]['Name']

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [7]:
df.loc[1, 'Name']

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [10]:
start = df.loc[1, 'Name'].find("(")

In [11]:
end = df.loc[1, 'Name'].find(")")

In [12]:
df.loc[1, 'Name'][0:start] + df.loc[1, 'Name'][end+1:]

'Cumings, Mrs. John Bradley '

In [ ]:
# Replace substring with Regex : regular expression
# * Means zero or more
# . means match any or more

#"\(.*\)"
# In windows we use : "\\" but we want that it will work in mac , windows, linux but when we want the code to ork in al the system we make use of "r"
df['Name'].str.replace(r"\(.*\)", "", regex=True).head() # here we are telling that replace anything which is starting with open bracket and ending with closing bracket with hello

0          Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley
2           Heikkinen, Miss. Laina
3    Futrelle, Mrs. Jacques Heath
4         Allen, Mr. William Henry
Name: Name, dtype: str

| Part | Meaning                                                              |
| ---- | -------------------------------------------------------------------- |
| `r`  | Raw string literal — tells Python **not to interpret** `\` as escape |
| `\(` | Escaped `(` — matches a literal opening parenthesis                  |
| `.*` | Dot `.` matches **any character**, and `*` means **zero or more**    |
| `\)` | Escaped `)` — matches a literal closing parenthesis                  |

In [ ]:
def is_valid_email(email):
    # Regex Breakdown:
    # ^[a-zA-Z0-9._%+-]+ : Alphanumeric + common symbols in username
    # @                  : Mandatory @ symbol
    # [a-zA-Z0-9.-]+     : Alphanumeric, dots, or hyphens in domain
    # \.[a-zA-Z]{2,}$    : Must end with a dot followed by 2 or more letters
    pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
    
    # re.fullmatch returns a Match object if valid, otherwise None
    if re.fullmatch(pattern, email):
        return True
    return False

# Test cases
emails = ["user@example.com", "invalid-email", "name.surname@sub.domain.org", "hello@ghail@abc.com"]
for e in emails:
    print(f"{e}: {'Valid' if is_valid_email(e) else 'Invalid'}")

# Spilt and Access Element

In [ ]:
# Access
df['Name'][0]

In [5]:
# split
df['Name'].str.split(",")[0]

['Braund', ' Mr. Owen Harris']

# Strip Spaces

In [ ]:
df['Name'].str.strip() # it removes the spaces

# Find Position of Substring

In [ ]:
df['Name'].str.find("Mr")

# -1 means it is not present Find Return the index of the letter

# .str.find("Mr")

# Searches for the first occurrence of "Mr" in each string.
# Returns the starting index of "Mr".
# Returns -1 if "Mr" is not present.

0       8
1       9
2      -1
3      10
4       7
       ..
886    -1
887    -1
888    -1
889     6
890     8
Name: Name, Length: 891, dtype: int64

In [ ]:
# Count the passengers with "Miss" in Name
count = df['Name'].str.contains("Miss").sum() # Here python add the boolean values, python treates false as 0  and true as 1
print("Number of 'Miss':", count)

Number of 'Miss': 182

In [12]:
data = {
    'Name': [
        'John Doe', 'Jane Smith', 'Emily Johnson',
        'Robert Brown', 'Anna-Marie Lee'
    ],
    'Email': [
        'john@example.com', 'jane.smith@work.org',
        'emily_j@data.net', 'robertb@yahoo.com',
        'anna.lee@company.co'
    ]
}

df = pd.DataFrame(data)

In [13]:
df.head()

             Name                Email
0        John Doe     john@example.com
1      Jane Smith  jane.smith@work.org
2   Emily Johnson     emily_j@data.net
3    Robert Brown    robertb@yahoo.com
4  Anna-Marie Lee  anna.lee@company.co

In [ ]:
df['Name'].str.pad(width=20, side='left', fillchar='-')

'''  
str.pad() in Pandas

str.pad() is used to increase the length of each string by adding a specified character (fillchar) to the left,
 right, or both sides until the string reaches the desired width.
'''

0    ------------John Doe
1    ----------Jane Smith
2    -------Emily Johnson
3    --------Robert Brown
4    ------Anna-Marie Lee
Name: Name, dtype: str

# Categorical Data in Pandas

### 📌 What is Categorical Data?

Categorical data is textual or labeled data that represents discrete categories.

# Interview Notes

- pd.Categorical() creates a categorical data type.

- Categories are stored once and represented internally by integer codes.

- Reduces memory usage for repeated text values.

- ordered=True enables meaningful comparisons and sorting.

- Commonly used for columns like priority, rating, size, gender, status, etc.

In [18]:
class_data = {
    "Name" : ["A", "B", "C", "D"],
    "Groups" : ["G1", "G2", "G3", "G4"]
}

In [19]:
class_df = pd.DataFrame(class_data)

In [20]:
class_df

  Name Groups
0    A     G1
1    B     G2
2    C     G3
3    D     G4

In [ ]:
# if we say i want all the column which are greater than G4
class_df['Groups']>"G4" # this does not make any sense since  we have not decided any order

0    False
1    False
2    False
3    False
Name: Groups, dtype: bool

In [ ]:
# Now We decide the oder from highest to lowest G3>G1>G2>G4
# now i we say df["Grops"]>"G4" ,Now the order is defined and when this operation run it will return true sinfror g1>g4 since we have alreadt define the order
#

In [ ]:
class_df.info() # here we say the data type of gruops is string

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Groups  4 non-null      str
dtypes: str(2)
memory usage: 196.0 bytes

In [ ]:
# Creatin of Categorical data as we discussed above for tis we make use of Categorical 

class_df['Groups_Cat'] = pd.Categorical(
    class_df['Groups'],  # 1st parameter accepts List, Tuple, NumPy array, or Pandas Series
    categories=['G3', 'G1', 'G2', 'G4'],  # Here we are defining the category order (lower t higher)
    ordered=True
)

class_df
class_df.info() # here we can see the groups_Cat is a new data type

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        4 non-null      str
 1   Groups      4 non-null      category
 2   Groups_Cat  4 non-null      category
dtypes: category(2), str(1)
memory usage: 580.0 bytes

In [36]:
class_df['Groups_Cat'].cat.categories

Index(['G3', 'G1', 'G2', 'G4'], dtype='str')

In [34]:
class_df['Groups_Cat'] > "G4" # now this will make sense becasue we have already decided the order and will give the correvt result based on the order we set

0    False
1    False
2    False
3    False
Name: Groups_Cat, dtype: bool

In [2]:
import pandas as pd
titanic_dataset_local_url = "titanic.csv"
df = pd.read_csv(titanic_dataset_local_url)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [5]:
df['Embarked'].unique() # the port where a passenger boarded the ship, indicated by a single-letter code
# C (Cherbourg)
# Q (Queenstown)
# S (Southampton)

<StringArray>
['S', 'C', 'Q', nan]
Length: 4, dtype: str

In [6]:
df['Embarked'] = df['Embarked'].fillna("N")

In [40]:
df['Embarked'].unique()
# C (Cherbourg) --> 1000000
# Q (Queenstown) --> 5000000
# S (Southampton) ---> 100000
# N --> Not provided ---> 000000

# N, S, C, Q

# Find all the passenger >  100000 > S

<StringArray>
['S', 'C', 'Q', nan]
Length: 4, dtype: str

In [7]:
df['Embarked_cust_cat']= pd.Categorical(
    df['Embarked'],
    categories=['N', 'S', 'C', 'Q'], # Custom order lower to higher (Ascending)
    ordered=True
)

In [8]:
df['Embarked_cust_cat'].cat.categories

Index(['N', 'S', 'C', 'Q'], dtype='str')

In [9]:
df['Embarked_cust_cat'] > 'S'

0      False
1       True
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889     True
890     True
Name: Embarked_cust_cat, Length: 891, dtype: bool

In [10]:
df['Embarked_cust_cat'].head()

0    S
1    C
2    S
3    S
4    S
Name: Embarked_cust_cat, dtype: category
Categories (4, str): ['N' < 'S' < 'C' < 'Q']

In [11]:
# how to get the codes of the category which we have set 
df['Embarked_cust_cat'].cat.codes.head()

0    1
1    2
2    1
3    1
4    1
dtype: int8

In [ ]:
# df['Sex']

# i want you to convert the values of Sex column and encode them in 0 & 1

df['Sex'].unique()

In [14]:
df['Sex_cat_custom'] = df['Sex'].astype('category').cat.codes
df['Sex_cat_custom'].head()
# df['Sex_cat_custom'] = df['Sex'].replace(['female', 'male'], [0, 1])

# df['Sex_cat_custom'] = df['Sex'].apply(lambda sex: 1 if sex == 'male' else 0)

0    1
1    0
2    0
3    0
4    1
Name: Sex_cat_custom, dtype: int8

In [15]:
df = pd.DataFrame({
    'event': ['Concert', 'Conference', 'Wedding'],
    'date': ['2025-01-01', '2025-03-15', '2025-07-20']
})

In [16]:
df.info() # in the result we can see the date alos belong to str

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   event   3 non-null      str
 1   date    3 non-null      str
dtypes: str(2)
memory usage: 180.0 bytes

In [17]:
df

        event        date
0     Concert  2025-01-01
1  Conference  2025-03-15
2     Wedding  2025-07-20

In [20]:
df['date_pandas'] = pd.to_datetime(df['date']) # pd.dateTime is used as we can see in output the data type is different than str
# format: optional format (e.g. '%d/%m/%Y')

df

        event        date date_pandas
0     Concert  2025-01-01  2025-01-01
1  Conference  2025-03-15  2025-03-15
2     Wedding  2025-07-20  2025-07-20

In [21]:
# To extract year
df['date_pandas'].dt.year

0    2025
1    2025
2    2025
Name: date_pandas, dtype: int32

In [22]:
# To extract month
df['date_pandas'].dt.month

0    1
1    3
2    7
Name: date_pandas, dtype: int32

In [23]:
# To extract day
df['date_pandas'].dt.day

0     1
1    15
2    20
Name: date_pandas, dtype: int32

In [24]:
# To extract Weekday
df['date_pandas'].dt.weekday

0    2
1    5
2    6
Name: date_pandas, dtype: int32

In [25]:
# To extract day name
df['date_pandas'].dt.day_name()

0    Wednesday
1     Saturday
2       Sunday
Name: date_pandas, dtype: str

In [26]:
df[df['date_pandas'] > '2025-04-01']

     event        date date_pandas
2  Wedding  2025-07-20  2025-07-20

In [27]:
df[df['date_pandas'].between('2025-01-01', '2025-06-01')]

        event        date date_pandas
0     Concert  2025-01-01  2025-01-01
1  Conference  2025-03-15  2025-03-15

# Creating Datetime Ranges

Other frequencies:

'M' → month end

'MS' → month start

'W' → weekly

'H', 'T', 'S' → hour, minute, second

In [ ]:
pd.date_range(start='2026-02-01', end='2026-02-10', freq='D') # here D means all the dates

In [ ]:
pd.date_range(start='2024-01-01', end='2024-03-10', freq='ME') #ME=month end

In [ ]:
pd.date_range(start='2024-01-01', end='2024-03-10', freq='MS') # ms=month start

# Date Arithmetic

In [28]:
df['next_week'] = df['date_pandas'] + pd.Timedelta(days=7)

In [29]:
pd.Timedelta(days=7)

Timedelta('7 days 00:00:00')

In [30]:
pd.Timestamp.today()

Timestamp('2026-07-21 09:04:14.905556')

In [31]:
df.head()

        event        date date_pandas  next_week
0     Concert  2025-01-01  2025-01-01 2025-01-08
1  Conference  2025-03-15  2025-03-15 2025-03-22
2     Wedding  2025-07-20  2025-07-20 2025-07-27

In [32]:
df['days_to_event'] = df['date_pandas'] - pd.Timestamp.today()

In [33]:
df.head()

        event        date date_pandas  next_week              days_to_event
0     Concert  2025-01-01  2025-01-01 2025-01-08 -567 days +14:55:36.322428
1  Conference  2025-03-15  2025-03-15 2025-03-22 -494 days +14:55:36.322428
2     Wedding  2025-07-20  2025-07-20 2025-07-27 -367 days +14:55:36.322428

# Pandass Completed ===========================================

In [34]:
#Push to git

# `pd.Categorical()` in Pandas

`pd.Categorical()` is used to convert data into **categorical data**, which helps save memory and makes operations like sorting, grouping, and comparisons more efficient.

---

# Syntax

```python
pd.Categorical(
    values,
    categories=None,
    ordered=False,
    dtype=None
)
```

---

# Parameters

| Parameter | Required? | Purpose |
|-----------|-----------|---------|
| `values` | ✅ Yes | The data you want to convert into categorical values. |
| `categories` | ❌ No | Specify the allowed categories and their order. |
| `ordered` | ❌ No | Whether the categories have an order (`True` or `False`). |
| `dtype` | ❌ No | Specify a categorical data type (advanced usage). |

---

# 1. `values` (Required)

This is the **data that will become categorical**.

It can be:

- List
- Tuple
- NumPy Array
- Pandas Series

## Example

```python
import pandas as pd

cities = pd.Categorical(
    ["Delhi", "Mumbai", "Delhi", "Pune"]
)

print(cities)
```

### Output

```python
['Delhi', 'Mumbai', 'Delhi', 'Pune']
Categories (3, object): ['Delhi', 'Mumbai', 'Pune']
```

Here,

```python
["Delhi", "Mumbai", "Delhi", "Pune"]
```

is the **`values`** parameter.

---

# 2. `categories`

Suppose your data is:

```python
["Gold", "Silver", "Gold"]
```

You know that the possible categories are:

- Gold
- Silver
- Bronze

You can specify them explicitly.

## Example

```python
grades = pd.Categorical(
    ["Gold", "Silver", "Gold"],
    categories=["Bronze", "Silver", "Gold"]
)

print(grades)
```

### Output

```python
['Gold', 'Silver', 'Gold']
Categories (3, object): ['Bronze', 'Silver', 'Gold']
```

### Notice

Although `"Bronze"` doesn't appear in the data, it is still stored as a valid category.

---

## Why use `categories`?

### Without specifying categories

```python
pd.Categorical(["A", "B", "A"])
```

Pandas automatically discovers:

```text
Categories:
A
B
```

---

### With specifying categories

```python
pd.Categorical(
    ["A", "B", "A"],
    categories=["A", "B", "C", "D"]
)
```

Now Pandas knows that all four values are valid categories, even if some are not present in the data.

---

# 3. `ordered`

By default,

```python
ordered=False
```

This means the categories have **no ranking**.

## Example

```python
grades = pd.Categorical(
    ["High", "Medium", "Low"],
    ordered=False
)
```

Here,

```text
High > Medium
```

has **no meaning**.

---

## Using `ordered=True`

```python
grades = pd.Categorical(
    ["High", "Medium", "Low"],
    categories=["Low", "Medium", "High"],
    ordered=True
)
```

Now Pandas understands:

```text
Low < Medium < High
```

Comparisons now work correctly.

### Example

```python
grades[0] > grades[1]
```

Conceptually,

```text
High > Medium
```

returns

```python
True
```

Sorting also follows the category order.

---

# 4. `dtype`

This is an **advanced parameter**.

Instead of writing:

```python
pd.Categorical(
    values,
    categories=["A", "B"],
    ordered=True
)
```

you can create a reusable categorical data type.

## Example

```python
from pandas.api.types import CategoricalDtype

grade_type = CategoricalDtype(
    categories=["A", "B", "C"],
    ordered=True
)
```

Now reuse it:

```python
pd.Categorical(
    ["A", "B", "A"],
    dtype=grade_type
)
```

This is useful when multiple DataFrames should use the same category definition.

---

# Complete Example

```python
import pandas as pd

grades = pd.Categorical(
    values=["A", "B", "A", "C"],
    categories=["A", "B", "C", "D"],
    ordered=True
)

print(grades)
```

### Output

```python
['A', 'B', 'A', 'C']
Categories (4, object): ['A' < 'B' < 'C' < 'D']
```

---

# Interview Notes

## `pd.Categorical()` Parameters

| Parameter | Description |
|-----------|-------------|
| `values` | The data to convert into categories. **Required.** |
| `categories` | Defines all possible category values. Optional. |
| `ordered` | Specifies whether the categories have an order (`True`/`False`). Default is `False`. |
| `dtype` | A predefined categorical data type for advanced reuse. Optional. |

---

# Quick Memory Trick

Think of the parameters like this:

```python
pd.Categorical(
    values,        # What is my data?
    categories,    # What are all the allowed values?
    ordered,       # Is there a ranking?
    dtype          # Reuse an existing categorical type (advanced)
)
```

---

# Real-World Usage

In most real-world projects, you'll commonly use these three parameters:

- ✅ `values`
- ✅ `categories`
- ✅ `ordered`

The `dtype` parameter is mainly used when you want multiple DataFrames or Series to share the same categorical definition.

---

# Summary

| Parameter | Purpose | Default |
|-----------|---------|---------|
| `values` | Data to convert into categorical values | **Required** |
| `categories` | Defines all possible categories | `None` |
| `ordered` | Specifies whether categories have an order | `False` |
| `dtype` | Reuse an existing categorical data type | `None` |